### ISSUE TITLE
Please change repository name to `stable-diffusion-webui-ko_KR`

### ISSUE THREAD

**Issue by kubinka0505** [36DB/stable-diffusion-webui-localization-ko_KR#1]
No offense, but it just doesn't look neat comparing it to other localizations repositories...

---

<img src=https://user-images.githubusercontent.com/30776937/201520014-b751ab19-216b-42ba-bfeb-01667d1d6f90.png height=700>

**Comment by 36DB** [comment]
@kubinka0505 Done. Please reply if some problems happen after the renaming process.

**Comment by kubinka0505** [comment]
I think everything is alright, thanks. 🙂

**Comment by kubinka0505** [comment]
God, I'm clingy. You can *fix "typo"* the `ReadMe.md` if you want. 😅 

---

<img src=https://user-images.githubusercontent.com/30776937/201523317-74a5b27d-6393-4016-9bdd-184a1df8bca4.png wdith=400>

**Comment by 36DB** [comment]
@kubinka0505 Silly me, fixing that too 😅
